import type { SchemaEditorLabels } from './types.ts';

export const defaultLabels: SchemaEditorLabels = {
	title: 'Title',
	propertyName: 'Field name',
	description: 'Description',
	format: 'Format',
	examples: 'Examples',
	required: 'Required',
	settings: '…',
	nullable: 'Nullable',
	removeProperty: 'Remove field',
	addProperty: 'New Field',
	allOf: 'All of',
	anyOf: 'Any of',
	oneOf: 'One of',
	option: 'Option',
	addOption: 'Add option',
	removeOption: 'Remove option',
	rootElement: 'Root Element',
	arrayItem: 'Array Item',
	unspecifiedType: 'Unspecified',
	minimum: 'Minimum',
	maximum: 'Maximum',
	exclusiveMinimum: 'Exclusive minimum',
	exclusiveMaximum: 'Exclusive maximum',
	multipleOf: 'Multiple of',
	minLength: 'Min length',
	maxLength: 'Max length',
	pattern: 'Pattern',
	enum: 'Enum',
	minItems: 'Min items',
	maxItems: 'Max items',
	minProperties: 'Min properties',
	maxProperties: 'Max properties'
};
